#!/bin/sh

HOST_CONFIG_FILE="/etc/otelcol/config.yaml"

log() {
  echo "$1" | systemd-cat
}

REPORTING_ARG=""
if [ "$(snapctl get reporting-enabled)" = "0" ]; then
  log "Launching with reporting disabled"
  REPORTING_ARG="-disable-reporting"
else
  log "Launching with reporting enabled"
fi

launch_strict() {
  CONFIG_FILE="$SNAP/etc/config.yaml"

  if snapctl is-connected etc-otelcol-config && [ -r "$HOST_CONFIG_FILE" ]; then
    log "Launching with config from the host filesystem"
    CONFIG_FILE="$HOST_CONFIG_FILE"
  else
    log "Launching with minimal default config from the snap"
  fi

  exec "$SNAP/bin/otelcol" --config "$CONFIG_FILE" $REPORTING_ARG
}

launch_strict
