name: opentelemetry-collector
version: '0.119.0'
summary: Vendor-agnostic way to receive, process and export telemetry data.
description: |
  Designed to collect, process, and export telemetry data such as metrics, logs,
  and traces from various sources to multiple destinations.

contact: jose.masson@canonical.com
base: core24


platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
  arm64:
    build-on: [arm64]
    build-for: [arm64]

# confinement: devmode # use 'strict' once you have the right plugs and slots
confinement: strict # use 'strict' once you have the right plugs and slots

plugs:
  etc-otelcol-config:
    interface: system-files
    read:
      - /etc/otelcol/config.yaml

  logs:
    interface: content
    target: $SNAP/shared-logs

  proc-sys-kernel-random:
    interface: system-files
    read:
      - /proc/sys/kernel/random/write_wakeup_threshold
      - /proc/sys/kernel/random/read_wakeup_threshold
      - /proc/sys/kernel/random/poolsize
      - /proc/sys/kernel/random/urandom_min_reseed_secs
      # Added because of: https://github.com/canonical/grafana-agent-operator/issues/23
      - /proc/spl/kstat/zfs
      - /sys/fs/btrfs
      - /proc/sys/kernel/threads-max
apps:
  opentelemetry-collector:
    daemon: simple
    # command: bin/otelcol --config $SNAP/etc/config.yaml
    command: command-wrapper
    install-mode: disable
    restart-condition: on-failure
    plugs:
      - network-bind
      - time-control
      - hardware-observe
      - mount-observe
      - network-observe
      - system-observe
      - log-observe
      - etc-otelcol-config
      - proc-sys-kernel-random
      # We use home plug since it has the dac_read_search capability enabled.
      # without this, we may face this issue while reading logs in /var/log
      # https://bugs.launchpad.net/snapd/+bug/2098780
      - home

parts:
  wrapper:
    plugin: dump
    source: ./snap
    source-type: local
    override-build: |
      cp local/command-wrapper $CRAFT_PART_INSTALL/
  opentelemetry-collector:
    plugin: nil
    source: https://github.com/open-telemetry/opentelemetry-collector-releases
    source-type: git
    source-tag: v0.119.0
    build-snaps:
      - go/1.23/stable
    build-environment:
      - CGO_ENABLED: 0
      - GOOS: linux
    override-build: |
      make build DISTRIBUTIONS="otelcol"
      install -D distributions/otelcol/_build/otelcol ${CRAFT_PART_INSTALL}/bin/otelcol
      install -D distributions/otelcol/config.yaml ${CRAFT_PART_INSTALL}/etc/config.yaml
